#lets see how this works | creates to build jobs
matrix:
  include:
    #android app 
    - language: android
      jdk: oraclejdk8
      node_js:
        - 6.9.1
      sudo: true
      branches:
        only:
          - master
      android:
        components:
          - build-tools-26.0.2
      install:
        - sudo apt-get install npm
        - sudo apt-get install node
        - cd speakUpApp
        - sudo npm install
        - sudo npm cache clean
        - sudo npm install -g cordova
        - echo y | android update sdk -u --filter android-22,android-26
        - sudo npm cache clean -f
        - sudo npm install -g n
        - sudo n stable
        - cordova build
      script:
        - sudo cordova prepare
        - sudo cordova build android --release
      release:
        - exit 0
      before_deploy:
        - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
      deploy:
        provider: releases
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure GITHUB_TOKEN
        file: "/home/travis/build/voxsar/speakUp/speakUpApp/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk"
        keep-history: true
        on:
          branch: master
          tags: true
  
    #ios deployment test | works but sandboxed debug file cannot be used
    - language: objective-c
      os: osx
      osx_image: xcode9.2
      install:
        - brew install npm
        - brew install node
        - cd speakUpApp
        - sudo npm install
        - sudo npm cache clean
        - sudo npm install -g cordova
        - sudo npm cache clean -f
        - sudo npm install -g n
        - sudo n stable
        #- cordova build
      script:
        - echo y | sudo cordova platform add ios --no-insight
        - sudo cordova build ios --release --no-insight
      release:
        - exit 0
      before_deploy:
        - git config --local user.name "voxsar"
        - git config --local user.email "vo.x@outlook.com"
        - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
      deploy:
        provider: releases
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure GITHUB_TOKEN
        file: "/Users/travis/build/voxsar/speakUp/speakUpApp/platforms/ios/build/emulator/speakUpApp.app"
        keep-history: true
        on:
          branch: master
          tags: true
notifications:
  email: false
 
